---
title: "GF0604 Procesamiento de datos geográficos 2021-I. Proyecto 02"
author: 
- name: Manuel Vargas
  url: https://github.com/mfvargas
  affiliation: Universidad de Costa Rica
  affiliation_url: https://www.ucr.ac.cr/
- name: Christian Birkel
  affiliation: Universidad de Costa Rica
  affiliation_url: https://www.ucr.ac.cr/
description: |
  Curso GF0604 Procesamiento de datos geográficos. Escuela de Geografía, Universidad de Costa Rica. Primer ciclo lectivo 2021. Proyecto 02.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

### Fecha de entrega y entregables
La fecha y hora límite para la entrega de este proyecto es el **jueves 29 de julio de 2021 a las 12:00 p.m.**

Debe escribir un documento R Markdown y publicarlo como una **página web (HTML) en GitHub Pages** con los contenidos que se especifican seguidamente y que se presentarán en un tablero de control (*dashboard*) que construirá mediante el paquete [flexdashboard](https://pkgs.rstudio.com/flexdashboard/). Entregue su tarea a través de la plataforma Mediación Virtual, especificando la dirección de su sitio web.

**El proyecto puede realizarse en grupos de hasta tres estudiantes.**

### Objetivos
Al finalizar esta tarea, el estudiante será capaz de:

1. Realizar operaciones en el lenguaje R con datos de atributos, datos espaciales y geometrías, tanto en el modelo vectorial como en el raster.
2. Visualizar los resultados con tablas, gráficos y mapas interactivos.
3. Publicar los resultados como páginas web generadas a partir de documentos R Markdown, mediante el paquete ```flexdashboard```.

### Datos
Para desarrollar el proyecto, utilice los siguientes conjuntos de datos:

- Registros de presencia de orquídeas (familia [*Orchidaceae*](https://es.wikipedia.org/wiki/Orchidaceae)) de Costa Rica, disponible en [https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv](https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv).  
- Cantones de Costa Rica, disponible en [https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson](https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson).  
- Provincias de Costa Rica, disponible en [https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson](https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson).

### Desarrollo

0. (5%) Descarte los registros con un valor mayor que 1000 (mil) en el campo ```coordinateUncertaintyInMeters```. **No elimine los registros con un valor vacío o NA en este campo (vamos a asumir que son aceptables).**

Elabore un tablero de control con el paquete ```flexdashboard``` con los siguientes elementos:

1. (15%) Etiquetas que muestren:  
- La cantidad total de especies.  
- La cantidad total de géneros.  
- La cantidad total de registros de presencia.

2. (20%) Tabla ```DT``` que muestre para cada registro: la especie, la fecha, la provincia y el cantón en el que se ubica.  

3. (20%) Gráfico ```plotly``` de pastel con la cantidad de registros y porcentaje correspondiente para las 10 especies con más registros. Los registros de las especies restantes deben agruparse en una categoría llamada "Otras".

4. (20%) Capa ```leaflet``` agrupada (*clustered*) de todos los registros de presencia de orquídeas. La ventana emergente (*popup*) asociada a cada registro debe mostrar, al menos, el nombre de la especie, la fecha, la provincia y el cantón en donde se ubica el registro.

5. (20%) Capa ```leaflet``` raster que muestre la cantidad de especies en cada celda (elija una resolución adecuada).

Consideraciones generales:

- Organice los diferentes elementos del tablero de control de manera que puedan visualizarse de la mejor manera posible. Elija con cuidado los colores de las capas, leyendas y demás elementos visuales. También la cantidad de filas, columnas y páginas del tablero.  
- Elija la cantidad de mapas en los que va a presentar las diferentes capas.  
- Cada mapa deben contar con:
    - Al menos una capa base (OSM, ESRI Images, Stamen, etc.).  
    - Un control para activar y desactivar las capas.  
    - Leyendas que muestren el significado de los colores en cada capa.
    
    